[package]
name = "identity_registry"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = "23.0.3"  # No testutils for production build

[dev-dependencies]
soroban-sdk = { version = "23.0.3", features = ["testutils"] }  # testutils only for tests